### ISSUE TITLE
Nothing working anymore

### ISSUE THREAD

**Issue by Charlie-Root** [athombv/nl.klikaanklikuit.zigbee#5]
After the last update of Homey KAKU is not responding anymore. I restarted both Homey and the KAKU controller without luck.

**Comment by jeroenvollenbrock** [comment]
Could you please take another look at our [contributing guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and open a new issue? The more information we have, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact us through [support@athom.com](mailto:support@athom.com) instead of using the bug tracker
